### ISSUE TITLE
Support for EGL (without X11)

### ISSUE THREAD

**Issue by loganmc10** [anholt/linux#37]
Forgive me if I get some of the terminology wrong. I can't seem to get this driver to work without a running X server. Is that how it is supposed to be? Is there support for running applications using EGL without having an X server running?

If so, how would one go about doing things like setting the resolution?

**Comment by vanfanel** [comment]
@loganmc10 : EGL without X11 is perfectly possible. SDL2 on the Pi uses dispmanx for the EGL context, and so does RetroArch.
Look in /opt/vc/src/hello_pi for examples.
For EGL/GLES on KMS/DRM, see the great KMSCube example by Robert Clark:
https://github.com/robclark/kmscube

**Comment by loganmc10** [comment]
I was under the impression that the dispmanx stuff doesn't work with this driver, is that wrong?

**Comment by vanfanel** [comment]
You are right. I came to post a question myself, saw your question and didn't read the "this driver" part. Sorry.
I am _almost_ sure that the MESA driver is compatible with a KMS context, however, so the kmscube should run on the Pi if you boot it in KMS mode instead of dispmanx and have the necessary libs installed.

**Comment by sirspudd** [comment]
@loganmc10 The Qt eglfs driver (which has kms provisioning) works great against both the proprietary driver and vc4. I simply switched from one impl to the other in Qt 5.7, and eglfs works perfectly with both driver sets. (It does require a recompile though as the EGL helpers are different)
